@startuml
interface ShootStrategy {
    + List<BaseBullet> shoot(AbstractAircraft aircraft)
}
class DirectShootStrategy implements ShootStrategy {
    + List<BaseBullet> shoot(AbstractAircraft aircraft)
}
class FanShootStrategy implements ShootStrategy {
    + List<BaseBullet> shoot(AbstractAircraft aircraft)
}
class CircleShootStrategy implements ShootStrategy {
    + List<BaseBullet> shoot(AbstractAircraft aircraft)
}
abstract class AbstractAircraft {
    - ShootStrategy strategy
    + void setStrategy(ShootStrategy strategy)
    + List<BaseBullet> shoot()
}
class HeroAircraft extends AbstractAircraft {
    + void setStrategyForTime(ShootStrategy newStrategy, int durationMillis)
}
class BossEnemy extends AbstractAircraft

AbstractAircraft --> ShootStrategy : uses
@enduml